# Default values for application-library-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# GLOBAL
nameOverride: hotel
fullnameOverride: microservice-hotel
sistema: booking
component: api           # [api|domian|data|controller]
namespaceOverride: micro

# IMAGE
image:  
  repository: jsa4000
  name: hotel-microservice
  tag: 0.0.1-SNAPSHOT
  pullPolicy: Always #IfNotPresent
  # pullSecrets: {}

replicaCount: 1

# CONTAINER PORT
containerPort: 8080    

# STRATEGY UPDATE
strategy:
  type: RollingUpdate
  #rollingUpdate:
  #  maxUnavailable: 25%
  #  maxSurge: 1

# HEALTH CHECKS
readinessProbe:
  httpGet:
    path: /management/health/readiness
    port: http
  initialDelaySeconds: 60
  timeoutSeconds: 3
  failureThreshold: 2

livenessProbe:
  httpGet:
    path: /management/health/liveness
    port: http
  initialDelaySeconds: 80
  timeoutSeconds: 3
  failureThreshold: 2

# RESOURCES
resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "1000m"

# ENVIRONMENT VARIABLES
env:
- name: SPRING_PROFILES_ACTIVE
  value: docker,jsonlog
- name: JAVA_OPTS
  value: -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80  
- name: SPRING_CONFIG_ADDITIONAL_LOCATION
  value: file:/opt/app/config/application.yml
- name: OPENTRACING_JAEGER_ENABLED
  value: "false"
- name: SECRET_JWT_PUBLIC_KEY
  valueFrom:
    secretKeyRef:
      name: microservice-hotel
      key: jwt.publicKey
- name: SECRET_DATABASE_PASSWORD
  valueFrom:
    secretKeyRef:
      name: microservice-hotel
      key: database.password
- name: SECRET_DATABASE_USERNAME
  valueFrom:
    secretKeyRef:
      name: microservice-hotel
      key: database.username

# SECRETS
secrets:
  enabled: true
  create: true
  sealedSecrets:
    enabled: true

# CONFIGMAP
configMap:
  enabled: true
  create: true

# SERVICE
service:
  type: ClusterIP
  port: 80

# INGRESS
ingress: 
  public:
    enabled: true
    hosts:
      - "*"
    attempts: 3
    perTryTimeout: 2s
    ports:
      - name: http
        number: 80
        protocol: HTTP
  private:
    enabled: false

# TRAEFIK
traefik:
  enabled: false
  path: /hotel

# SERVICE MONITOR 
serviceMonitor:
  enabled: false
  release: prometheus
  endpoints:
  - interval: 30s
    port: http
    path: management/metrics

# SERVICE ENTRY
serviceEntry:
  enabled: false

# NODE SELECTOR
nodeSelector: {}

## TOLERATIONS
tolerations: []

## AFFINITY
affinity: 
  highAvailability: true
  nodeAffinity: {}
  podAffinity: {}
  podAntiAffinity: {}

# RBAC
rbac:
  enabled: true
  create: true

# NETWORK POLICY
networkPolicy:
  enabled: false

## HPA
autoscaling:
 enabled: false
# minReplicas: 1
# maxReplicas: 3
# metrics:
#  - type: Resource
#    resource:
#      name: cpu
#      target:
#        type: Utilization
#        averageUtilization: 75