spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://${SECRET_DATABASE_USERNAME}:${SECRET_DATABASE_PASSWORD}@mongodb.datastore.svc.cluster.local:27017/db_1

server:
  port: 8080
  max-http-header-size: 20000

mongock:
  enabled: true

web:
  clients:
    car:
      url: http://microservice-car.micro.svc.cluster.local
    flight:
      url: http://microservice-flight.micro.svc.cluster.local
    hotel:
      url: http://microservice-hotel.micro.svc.cluster.local

opentracing:
  jaeger:
    enabled: true
    enable-b3-propagation: true
    enable128-bit-traces: true
    probabilistic-sampler:
      sampling-rate: 0.0

logging:
  level:
    root: warn
    org.springframework: warn
    com.example: debug