server:
  port: 8080
  shutdown: graceful

management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint:
    health:
      show-components: always
      probes.enabled: true
      show-details: always
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
      base-path: /management
      path-mapping:
        prometheus: /metrics

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    es.gob.exteriores.mauc: DEBUG