kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql
  labels:
    app.kubernetes.io/name: mssql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi