apiVersion: v1
kind: Service
metadata:
  name: mssql
  labels:
    app.kubernetes.io/name: mssql
spec:
  clusterIP: None
  ports:
    - port: 1433
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: mssql