apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: booking-project
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  source:
    chart: sealed-secrets
    helm:
      values: |
        keyrenewperiod: 720h0m0s
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.1.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true