apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spa
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: booking-project
  destination:
    server: https://kubernetes.default.svc
    namespace: spa
  source:
    path: helm/components/spa
    repoURL: https://github.com/jsa4000/helm-charts.git
    targetRevision: deploy-istio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
