{{- define "spa-chart.secrets" -}}
{{- if and .Values.secrets.enabled .Values.secrets.create }}
{{- if eq .Values.secrets.sealedSecrets.enabled false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}-secret
{{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ include "spa-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}      
    app.kubernetes.io/component: {{ .Values.component }}  
    app.kubernetes.io/part-of: {{ .Values.sistema }}  
    app.kubernetes.io/managed-by: {{ .Release.Service }}  
    helm.sh/chart: {{ include "spa-chart.chart" . }}  
type: Opaque
data:
  {{- (.Files.Glob "secrets/*").AsSecrets | nindent 2 }}
{{- else }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secrets.name }}-secret
{{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
{{- end }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    app.kubernetes.io/name: {{ include "spa-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}      
    app.kubernetes.io/component: {{ .Values.component }}  
    app.kubernetes.io/part-of: {{ .Values.sistema }}  
    app.kubernetes.io/managed-by: {{ .Release.Service }}  
    helm.sh/chart: {{ include "spa-chart.chart" . }}  
spec:
  encryptedData:
  {{- (.Files.Glob "secrets/*").AsConfig | nindent 4 }}
{{- end }}
{{- end }}
{{- end -}}