apiVersion: builtin
kind: LabelTransformer
metadata:
  name: global-labels
labels:
  app.kubernetes.io/component: database
  app.kubernetes.io/managed-by: argocd
fieldSpecs:
- path: metadata/labels
  create: true