apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
spec:
  template:
    spec:
      containers:
        - name: mssql
          resources:
            requests:
              cpu: 250m
              memory: 512M
