{{- define "application-library.configmap" }}
{{- if and .Values.configMap.enabled .Values.configMap.create (not .Values.configMap.useExistingConfigMap) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application-library.fullname" . }}
  namespace: {{ include "application-library.namespace" . }}
  labels:
    {{- include "application-library.labels" . | nindent 4 }}
data:  
  {{- (.Files.Glob "config/*").AsConfig | nindent 2 }}
{{- end }}
{{- end }}