{{- define "application-library.secrets" }}
{{- if and .Values.secrets.enabled .Values.secrets.create (not .Values.secrets.useExistingSecret) }}
{{- if not .Values.secrets.sealedSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application-library.fullname" . }}
  namespace: {{ include "application-library.namespace" . }}
  labels:
    {{- include "application-library.labels" . | nindent 4 }} 
type: Opaque
data:
  {{- (.Files.Glob "secrets/*").AsSecrets | nindent 2 }}
{{- else }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "application-library.fullname" . }}
  namespace: {{ include "application-library.namespace" . }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    {{- include "application-library.labels" . | nindent 4 }}
spec:
  encryptedData:
  {{- (.Files.Glob "secrets/*").AsConfig | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}