{{- define "application-library.service" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "application-library.fullname" . }}
  namespace: {{ include "application-library.namespace" . }}
  labels:
    {{- include "application-library.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "application-library.selectorLabels" . | nindent 4 }}  
{{- end -}}